/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSAccessibilityElement.h"

@protocol NSAccessibilityStaticText <NSAccessibilityElement>
- (id)accessibilityValue;

@optional
- (struct _NSRange)accessibilityVisibleCharacterRange;
- (id)accessibilityAttributedStringForRange:(struct _NSRange)arg1;
@end

