/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSGestureRecognizer.h"

@interface NSGestureRecognizer (UXKit)
- (void)__stateChange:(id)arg1;
- (void)setGestureDidEndHandler:(id)arg1;
- (void)setGestureDidChangeHandler:(id)arg1;
- (void)setGestureDidBeginHandler:(id)arg1;
@end

