/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSImage.h"

@interface NSImage (UXKit)
- (id)resizableImageWithCapInsets:(struct NSEdgeInsets)arg1 resizingMode:(long long)arg2;
- (id)resizableImageWithCapInsets:(struct NSEdgeInsets)arg1;
@end

