/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSIndexPath.h"

@interface NSIndexPath (UXTableView)
+ (id)indexPathForRow:(long long)arg1 inSection:(long long)arg2;
@property(readonly, nonatomic) long long row;

// Remaining properties
@property(readonly, nonatomic) long long section;
@end

