/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UXKit/UXBarItem.h>

@class NSSet;

@interface UXTabBarItem : UXBarItem
{
    NSSet *_possibleTitles;
}

@property(copy, nonatomic) NSSet *possibleTitles; // @synthesize possibleTitles=_possibleTitles;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1;

@end

